spring:
   cloud:
      config:
         server:
            git:
               uri: D:\lab\netflix\demo\src\main\resources\config
               basedir: target/config
			   
---

spring:
  encrypt:
   key: foobar
   
---

spring:
  security:
    user:
       password: s3cret
